import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import type { PluggyConnect as PluggyConnectType } from 'react-pluggy-connect'
import dynamic from 'next/dynamic';

const PluggyConnect = dynamic(
  () => (import('react-pluggy-connect') as any).then((mod: { PluggyConnect: any; }) => mod.PluggyConnect),
  { ssr: false }
) as typeof PluggyConnectType

export default function Home() {

  const [connectToken, setConnectToken] = useState<string>()

  useEffect(() => {
    if (!connectToken) {
      const fetchToken = async () => {
        const response = await fetch('/api/connect-token')
        const { accessToken } = await response.json()
        setConnectToken(accessToken)
      }

      fetchToken()
    }
  })

  const onSuccess = (itemData: { item: any; }) => {
    console.log(itemData.item)
  }

  const onError = (error: any) => {
    console.log('There was an error: ', error)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pluggy My Expenses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Pluggy My Expenses!
        </h1>

        {
          connectToken ? 
            <PluggyConnect
              connectToken={connectToken}
              onSuccess={onSuccess}
              onError={onError}
              includeSandbox
            /> : 'Loading...'
        }
        
      </main>

      
    </div>
  )
}
